name: Cleanup unused imports (Biome)

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  prune-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      # Swap in prune-only config
      - name: Prepare Biome prune config
        run: |
          mv biome.json biome.full.json
          cp biome.prune.json biome.json

      # Run unsafe prune (only noUnusedImports due to prune config)
      - name: Remove unused imports
        run: pnpm biome check --write --unsafe --max-diagnostics 100000 .

      # Restore full config
      - name: Restore full Biome config
        run: mv -f biome.full.json biome.json

      - name: Commit changes (if any)
        id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: prune unused imports via Biome [skip ci]"
          file_pattern: |
            **/*.js
            **/*.mjs
            **/*.cjs

      # Job summary: which files changed
      - name: Summarize changed files
        if: steps.autocommit.outputs.changes_detected == 'true'
        run: |
          echo "### Files updated" >> $GITHUB_STEP_SUMMARY
          git show --name-status --pretty=oneline ${{ steps.autocommit.outputs.commit_hash }} | tail -n +2 >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Diffstat" >> $GITHUB_STEP_SUMMARY
          git show --stat ${{ steps.autocommit.outputs.commit_hash }} >> $GITHUB_STEP_SUMMARY
          git show ${{ steps.autocommit.outputs.commit_hash }} > pruned.patch

      - name: Upload diff artifact
        if: steps.autocommit.outputs.changes_detected == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pruned-diff
          path: pruned.patch

      # PR comment with changed files
      - name: Comment PR with changed files
        if: steps.autocommit.outputs.changes_detected == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const commit = process.env.COMMIT;
            const {data: files} = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: commit,
            });
            const list = files.files.map(f => `- ${f.status.toUpperCase()} ${f.filename}`).join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `**Biome prune:** files updated in ${commit}\n\n${list}`
            });
        env:
          COMMIT: ${{ steps.autocommit.outputs.commit_hash }}

      # Optional: run full check (non-blocking)
      - name: Biome check (full)
        run: pnpm biome check .
        continue-on-error: true
