name: Run Unit Tests (pnpm)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Running-Tests:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure pnpm only (no Yarn)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f yarn.lock ]; then
            echo "yarn.lock found. Remove it and migrate to pnpm."
            exit 1
          fi
          if jq -e '.packageManager | startswith("yarn@")' package.json >/dev/null 2>&1; then
            echo 'packageManager is set to Yarn. Set it to pnpm.'
            exit 1
          fi

      # Install pnpm FIRST so it's on PATH
      - name: Setup pnpm (latest)
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      # Node + pnpm cache for speed
      - name: Setup Node.js (LTS) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Print tool versions
        run: |
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # IMPORTANT: no extra "--" before flags; use pnpm exec to avoid arg mangling
      - name: Run tests with coverage
        run: pnpm run test

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.run_id }}
          path: coverage/**
          retention-days: 14
