name: Run Tests on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Jest cache
        uses: actions/cache@v4
        with:
          path: .jest-cache
          key: ${{ runner.os }}-jest-${{ hashFiles('package-lock.json', 'jest.config.*', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-jest-

      - name: Ensure Jest cache dir
        run: mkdir -p .jest-cache

      - name: Run tests with coverage (fail if <95%)
        run: |
          npm run test -- \
            --coverage \
            --cache .jest-cache \
            --coverageReporters=json-summary \
            --coverageReporters=text-summary \
            --coverageReporters=lcov \
            --coverageDirectory=coverage \
            --coverageThreshold='{"global":{"branches":95,"functions":95,"lines":95,"statements":95}}'

      - name: Upload coverage + cache
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.run_id }}
          path: |
            coverage/**
            .jest-cache/**
          retention-days: 14
