name: Run Tests on Push

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS) with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies 
        run: npm install

      - name: Run tests with coverage
        run: |
          npm run test -- \
            --coverage \
            --coverageReporters=json-summary \
            --coverageReporters=text-summary \
            --coverageReporters=lcov \
            --coverageDirectory=coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.run_id }}
          path: coverage/**
          retention-days: 14
