name: Weekly PNPM Updates

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Enforce pnpm; block Yarn to avoid PM drift
      - name: Verify no Yarn config present
        shell: bash
        run: |
          set -euo pipefail
          if [ -f yarn.lock ]; then
            echo "yarn.lock found. This workflow enforces pnpm. Remove yarn.lock and migrate."
            exit 1
          fi
          if jq -e '.packageManager | startswith("yarn@")' package.json >/dev/null 2>&1; then
            echo 'packageManager is set to Yarn. Set it to pnpm (e.g., "pnpm@10.x") or remove to proceed.'
            exit 1
          fi
          if grep -R --exclude-dir=node_modules -nE '\byarn( |$)' package.json packages/*/package.json 2>/dev/null | head -n1; then
            echo "Yarn command references found in package scripts. Replace with pnpm."
            exit 1
          fi

      # Install pnpm FIRST so it's in PATH for subsequent steps
      - name: Setup pnpm (latest)
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      # Node + pnpm cache for speed
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Print tool versions
        run: |
          node -v
          pnpm -v

      # Update deps: only minor/patch; block zod major
      - name: Update dependencies (minor/patch only; block zod major)
        shell: bash
        run: |
          set -euo pipefail
          pnpm dlx npm-check-updates@latest -u --target minor --reject 'zod'
          pnpm -w -r install --no-frozen-lockfile

      - name: Lint and test (if present)
        shell: bash
        run: |
          set -euo pipefail
          pnpm -w -r run lint --if-present
          pnpm -w -r run test --if-present -- --ci

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/weekly-pnpm-updates
          title: "chore: weekly dependency updates (pnpm, minor/patch)"
          commit-message: "chore: weekly dependency updates (pnpm, minor/patch)"
          body: |
            Automated weekly dependency refresh via pnpm.

            - Enforced pnpm@latest with caching.
            - Ran npm-check-updates with --target minor and --reject zod to avoid zod@4 while peers require zod^3.
            - Updated lockfile with pnpm -w -r install.
            - Lint/tests executed when available.
            - Guardrails fail the run if Yarn config/usage is detected (yarn.lock, packageManager=yarn, or yarn scripts).
          labels: dependencies
          signoff: false
          delete-branch: true
