name: weekly-npm-updates
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable Corepack for pnpm/yarn detection
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Detect package manager
        id: pm
        shell: bash
        run: |
          set -euo pipefail
          if [ -f pnpm-lock.yaml ]; then
            echo "pm=pnpm" >> "$GITHUB_OUTPUT"
            corepack enable
            corepack prepare pnpm@latest --activate
          elif [ -f yarn.lock ]; then
            echo "pm=yarn" >> "$GITHUB_OUTPUT"
            corepack enable
          else
            echo "pm=npm" >> "$GITHUB_OUTPUT"
          fi

      - name: Install npm-check-updates
        run: |
          case "${{ steps.pm.outputs.pm }}" in
            pnpm) pnpm add -Dw npm-check-updates ;;
            yarn) yarn add -D npm-check-updates ;;
            npm)  npm i -D npm-check-updates ;;
          esac

      - name: Bump dependencies safely
        shell: bash
        run: |
          set -euo pipefail
          PM="${{ steps.pm.outputs.pm }}"
          # Default: minor/patch only to avoid peer explosions
          # Allowlist majors can be added with --filter
          case "$PM" in
            pnpm) npx ncu --target minor -u ;;
            yarn) npx ncu --target minor -u ;;
            npm)  npx ncu --target minor -u ;;
          esac

          # Example: explicitly avoid zod major for now (until @openai/agents supports v4)
          # Remove this reject once agents supports zod@4
          npx ncu --reject zod -u

          # Optional: attempt majors for a vetted list
          # npx ncu --target latest -u --filter "@types/node,typescript"

          # Install & update lockfile using the correct PM
          if [ "$PM" = "pnpm" ]; then
            pnpm install --frozen-lockfile=false
          elif [ "$PM" = "yarn" ]; then
            yarn install
          else
            npm install
          fi

      - name: Run lint/tests (if present)
        run: |
          if [ "${{ steps.pm.outputs.pm }}" = "pnpm" ]; then
            pnpm run -r -w lint --if-present || true
            pnpm run -r -w test --if-present -- --ci || true
          else
            npm run lint --if-present || true
            npm test --if-present -- --ci || true
          fi

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/weekly-npm-updates
          title: "chore: weekly dependency updates (safe minor/patch)"
          commit-message: "chore: weekly dependency updates (safe minor/patch)"
          body: |
            Automated weekly dependency refresh.
            - Used npm-check-updates with --target minor and explicit rejects for breaking peers.
            - Installed with the repo's package manager and updated the lockfile.
            - Lint/tests executed if available.
          labels: dependencies
          signoff: false
          delete-branch: true
