name: Weekly NPM Updates

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Detect package manager first so we can cache correctly
      - name: Detect package manager
        id: pm
        shell: bash
        run: |
          set -euo pipefail
          if [ -f pnpm-lock.yaml ]; then
            echo "pm=pnpm" >> "$GITHUB_OUTPUT"
            echo "lockfile=pnpm-lock.yaml" >> "$GITHUB_OUTPUT"
            corepack enable
            corepack prepare pnpm@latest --activate
          elif [ -f yarn.lock ]; then
            echo "pm=yarn" >> "$GITHUB_OUTPUT"
            echo "lockfile=yarn.lock" >> "$GITHUB_OUTPUT"
            corepack enable
          else
            echo "pm=npm" >> "$GITHUB_OUTPUT"
            echo "lockfile=package-lock.json" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: ${{ steps.pm.outputs.pm }}
          cache-dependency-path: ${{ steps.pm.outputs.lockfile }}

      # Use ncu without committing it to devDependencies
      - name: Bump dependencies safely (minor/patch only)
        shell: bash
        run: |
          set -euo pipefail
          # Keep zod on v3 while @openai/agents requires it
          # IMPORTANT: single ncu run with --target minor to avoid accidental majors
          npx npm-check-updates@latest -u --target minor --reject 'zod'

          # Optional allowlist for specific majors. Example:
          # npx npm-check-updates@latest -u --target latest --filter '@types/node,typescript'

          PM="${{ steps.pm.outputs.pm }}"
          if [ "$PM" = "pnpm" ]; then
            pnpm install --frozen-lockfile=false
          elif [ "$PM" = "yarn" ]; then
            yarn install
          else
            npm install
          fi

      - name: Run lint/tests if present
        shell: bash
        run: |
          PM="${{ steps.pm.outputs.pm }}"
          if [ "$PM" = "pnpm" ]; then
            pnpm -w -r run lint --if-present || true
            pnpm -w -r run test --if-present -- --ci || true
          elif [ "$PM" = "yarn" ]; then
            yarn run lint --if-present || true
            yarn run test --if-present --ci || true
          else
            npm run lint --if-present || true
            npm test --if-present -- --ci || true

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/weekly-npm-updates
          title: "chore: weekly dependency updates (minor/patch)"
          commit-message: "chore: weekly dependency updates (minor/patch)"
          body: |
            Automated weekly dependency refresh.

            Notes:
            - Used npm-check-updates with --target minor to avoid breaking majors.
            - Explicitly rejected zod majors while @openai/agents peers zod ^3.
            - Installed with the detected package manager and refreshed the lockfile.
            - Lint/tests executed if available.
          labels: dependencies
          signoff: false
          delete-branch: true
